services:

  mysql_db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalogodb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mynetwork

  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - mynetwork

  ms-catalog:
    build: ./ms-catalog
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./ms-catalog:/app
    depends_on:
      - mysql_db
      - redis
    networks:
      - mynetwork

  ms-cart:
    build: ./ms-cart
    ports:
      - "5002:5002"
    env_file:
      - .env
    volumes:
      - ./ms-cart:/app
    depends_on:
      - mysql_db
      - redis
    networks:
      - mynetwork

  ms-inventory:
    build: ./ms-inventory
    ports:
      - "5003:5003"
    env_file:
      - .env
    volumes:
      - ./ms-inventory:/app
    depends_on:
      - mysql_db
      - redis
    networks:
      - mynetwork

  ms-payment:
    build: ./ms-payment
    ports:
      - "5004:5004"
    env_file:
      - .env
    volumes:
      - ./ms-payment:/app
    depends_on:
      - mysql_db
      - redis
    networks:
      - mynetwork

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    volumes:
      - ./api-gateway:/app
    depends_on:
      - ms-catalog
      - ms-cart
      - ms-inventory
      - ms-payment
    networks:
      - mynetwork

volumes:
  mysql_data:
  redis_data:

networks:
  mynetwork:
    driver: bridge