services:
  traefik:
    image: traefik:3.3.2
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "81:80" # Puerto
      - "8081:8080" # Dashboard web

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - mynetwork

  mysql_db:
    image: mysql:9.2.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalogodb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin:5.2.2
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - mysql_db
    networks:
      - mynetwork

  redis:
    image: redis:7.4.2
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

  ms-purchase:
    build: ./ms-purchase
    ports:
      - "5002:5002"
    volumes:
      - ./ms-purchase:/app
    depends_on:
      - mysql_db
      - redis
    networks:
      - mynetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-purchase.rule=Host(`ms-purchase.localhost`)"
      - "traefik.http.services.ms-purchase.loadbalancer.server.port=5002"

  ms-catalog:
    build: ./ms-catalog
    ports:
      - "5001:5001"
    volumes:
      - ./ms-catalog:/app
    depends_on:
      - mysql_db
      - redis
    networks:
      - mynetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-catalog.rule=Host(`ms-catalog.localhost`)"
      - "traefik.http.services.ms-catalog.loadbalancer.server.port=5001"
      # Circuit Breaker
      - "traefik.http.middlewares.circuitbreaker.retry.attempts=3"
      - "traefik.http.middlewares.circuitbreaker.retry.initialinterval=500ms"
      # Enlace del middleware al router
      - "traefik.http.routers.ms-catalog.middlewares=circuitbreaker"

  ms-cart:
    build: ./ms-cart
    ports:
      - "5002:5002"
    volumes:
      - ./ms-cart:/app
    depends_on:
      - mysql_db
      - redis
    networks:
      - mynetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-cart.rule=PathPrefix(`/ms-cart`)"
      - "traefik.http.services.ms-cart.loadbalancer.server.port=5002"
      # Circuit Breaker
      - "traefik.http.middlewares.circuitbreaker.retry.attempts=3"
      - "traefik.http.middlewares.circuitbreaker.retry.initialinterval=500ms"
      # Enlace del middleware al router
      - "traefik.http.routers.ms-cart.middlewares=circuitbreaker"

  ms-inventory:
    build: ./ms-inventory
    ports:
      - "5003:5003"
    volumes:
      - ./ms-inventory:/app
    depends_on:
      - mysql_db
      - redis
    networks:
      - mynetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-inventory.rule=Host(`ms-inventory.localhost`)"
      - "traefik.http.services.ms-inventory.loadbalancer.server.port=5003"
      # Circuit Breaker
      - "traefik.http.middlewares.circuitbreaker.retry.attempts=3"
      - "traefik.http.middlewares.circuitbreaker.retry.initialinterval=500ms"
      # Enlace del middleware al router
      - "traefik.http.routers.ms-inventory.middlewares=circuitbreaker"

  ms-payment:
    build: ./ms-payment
    ports:
      - "5004:5004"
    volumes:
      - ./ms-payment:/app
    depends_on:
      - mysql_db
      - redis
    networks:
      - mynetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-payment.rule=Host(`ms-payment.localhost`)"
      - "traefik.http.services.ms-payment.loadbalancer.server.port=5004"
      # Circuit Breaker
      - "traefik.http.middlewares.circuitbreaker.retry.attempts=3"
      - "traefik.http.middlewares.circuitbreaker.retry.initialinterval=500ms"
      # Enlace del middleware al router
      - "traefik.http.routers.ms-payment.middlewares=circuitbreaker"

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    volumes:
      - ./api-gateway:/app
    depends_on:
      - ms-catalog
      - ms-inventory
      - ms-payment
    networks:
      - mynetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gateway.rule=Host(`api-gateway.localhost`)"
      - "traefik.http.services.api-gateway.loadbalancer.server.port=5000"
      # Circuit Breaker
      - "traefik.http.middlewares.circuitbreaker.retry.attempts=3"
      - "traefik.http.middlewares.circuitbreaker.retry.initialinterval=500ms"
      # Enlace del middleware al router
      - "traefik.http.routers.api-gateway.middlewares=circuitbreaker"

volumes:
  mysql_data:
  redis_data:

networks:
  mynetwork:
    driver: bridge
