services:
  ms-cart:
    build: ./ms-cart
    ports:
      - "5004:5004"
    env_file:
      - .env
    depends_on:
      - mysql_db
    networks:
      - mynetwork

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    
    depends_on:
      - ms-cart
    networks:
      - mynetwork

  mysql_db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalogodb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/db_query.sql:/docker-entrypoint-initdb.d/db_query.sql
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge