services:
  ms-catalogo:
    build: ./ms-catalogo
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mysql_db
    networks:
      - mynetwork

  ms-cart:
    build: ./ms-cart
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      - mysql_db
    networks:
      - mynetwork


  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - ms-catalogo
    networks:
      - mynetwork

  mysql_db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalogodb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
