version: '3.8'

services:

  mysql_db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mynetwork

  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - mynetwork

  ms-catalog:
    build: ./ms-catalog
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - ./ms-catalog:/app
    depends_on:
      - mysql_db
      - redis
    networks:
      - mynetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-catalog.rule=Host(`ms-catalog.localhost`)"
      - "traefik.http.services.ms-catalog.loadbalancer.server.port=5001"
      - "traefik.http.routers.ms-catalog.middlewares=circuit-breaker@file,retry@file,max-conn@file"

  ms-purchase:
    build: ./ms-purchase
    ports:
      - "5002:5002"
    env_file:
      - .env
    volumes:
      - ./ms-purchase:/app
    depends_on:
      - mysql_db
      - redis
    networks:
      - mynetwork

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-purchase.rule=Host(`ms-purchase.localhost`)"
      - "traefik.http.services.ms-purchase.loadbalancer.server.port=5002"
      - "traefik.http.routers.ms-purchase.middlewares=circuit-breaker@file,retry@file,max-conn@file"
  ms-inventory:
    build: ./ms-inventory
    ports:
      - "5003:5003"
    env_file:
      - .env
    volumes:
      - ./ms-inventory:/app
    depends_on:
      - mysql_db
      - redis
    networks:
      - mynetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-inventory.rule=Host(`ms-inventory.localhost`)"
      - "traefik.http.services.ms-inventory.loadbalancer.server.port=5003"
      - "traefik.http.routers.ms-inventory.middlewares=circuit-breaker@file,retry@file,max-conn@file"

  ms-payment:
    build: ./ms-payment
    ports:
      - "5004:5004"
    env_file:
      - .env
    volumes:
      - ./ms-payment:/app
    depends_on:
      - mysql_db
      - redis
    networks:
      - mynetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-payment.rule=Host(`ms-payment.localhost`)"
      - "traefik.http.services.ms-payment.loadbalancer.server.port=5004"
      - "traefik.http.routers.ms-payment.middlewares=circuit-breaker@file,retry@file,max-conn@file"

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    volumes:
      - ./api-gateway:/app
    depends_on:
      - ms-catalog
      - ms-purchase
      - ms-inventory
      - ms-payment
    networks:
      - mynetwork
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gateway.rule=Host(`api-gateway.localhost`)"
      - "traefik.http.services.api-gateway.loadbalancer.server.port=5000"
      - "traefik.http.routers.api-gateway.middlewares=circuit-breaker@file,retry@file,max-conn@file"


  traefik:
    image: traefik:3.3.2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.file.filename=/dynamic_conf/traefik_dynamic.yml"
    ports:
      - "81:80" # Port
      - "8081:8080" # Web UI
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik_dynamic.yml:/dynamic_conf/traefik_dynamic.yml"
    networks:
      - mynetwork


volumes:
  mysql_data:
  redis_data:

networks:
  mynetwork:
    driver: bridge