version: '3'
services:
  catalogo:
    build: ./catalogo
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mysql_db

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - catalogo

  mysql_db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalogodb

