http:
  middlewares:
    circuit-breaker:
      circuitBreaker:
        expression: "LatencyAtQuantileMS(50.0) > 100"
        fallbackDuration: "10s"
    retry:
      retry:
        attempts: 3
    maxconn:
      maxConn:
        amount: 10
        extractorFunc: "request.host"